### ISSUE TITLE
Flash/ leap highlighting is hard to read

### ISSUE THREAD

**Issue by artsbentley** [dotsilas/darcubox-nvim#2]
### What: 
highlighting of results is almost invisible when using custom search based plugins

### When: 
using plugins like https://github.com/folke/flash.nvim and https://github.com/ggandor/leap.nvim

See below for an example, the letters with yellow highlighting are almost impossible to read:
<img width="652" alt="image" src="https://github.com/dotsilas/darcubox-nvim/assets/86831689/30076cc0-66e6-4bdf-b8c2-cf8e1aae639b">

**Comment by gopyts** [comment]
Hello! I made a modification to the Search and Substitute groups that I think improve vision. Can you update the theme and confirm if it improved in your side?

![image](https://github.com/dotsilas/darcubox-nvim/assets/84829590/8dd07f60-8d84-4279-b98b-2269bf0b4233)

**Comment by artsbentley** [comment]
> Hello! I made a modification to the Search and Substitute groups that I think improve vision. Can you update the theme and confirm if it improved in your side?
> 


Amazing, works on my end too. Thanks!
