### ISSUE TITLE
Lack of coloring for HTML

### ISSUE THREAD

**Issue by vinoff** [dotsilas/darcubox-nvim#3]
Here are 2 screenshots comparing Gruvbox with Darcubox. This is just an example, but I find Darcubox really poor. in that regard Most things are not colored yet.

Gruvbox:
![gruvbox](https://github.com/dotsilas/darcubox-nvim/assets/90382765/a3ef5587-e192-4161-b8bc-d848e3e2a051)

Darcubox:
![darcubox](https://github.com/dotsilas/darcubox-nvim/assets/90382765/09135667-b48c-401d-90cb-3c0c2ff88197)

I do really like Darcubox though. It is becoming my favorite colorscheme! If support for that were added, Id be using it 100%. I also find that sometimes, even in Javascript, it is missing some syntax?

**Comment by gopyts** [comment]
Hi! I've added highlighting to the html tags and javascript attributes which I think can improve readability a bit.

![image](https://github.com/dotsilas/darcubox-nvim/assets/84829590/2e569e6a-8131-4174-abb1-49b23450173f)

|before|Now|
|:---|---:|
| ![image](https://github.com/dotsilas/darcubox-nvim/assets/84829590/5ffb8051-d99d-4234-a719-ba5fa940cddd) | ![image](https://github.com/dotsilas/darcubox-nvim/assets/84829590/f182968e-d5cc-4790-a814-f02f7c54effd) |
